stages:
  - test
  - docs
  - deploy

image: robert96/graphwalker-cli:4.0.0

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - pip3 install -r requirements.txt --user
  - pip3 install -r requirements-dev.txt

unit tests:
  stage: test
  tags:
    - docker
  artifacts:
    paths:
      - coverage/
  script:
    - pytest tests/unit -s -v --cov=altwalker --cov-report term --cov-report html:coverage/ altwalker/
  after_script:
    - pip3 install coverage-badge
    - coverage-badge -o coverage/coverage.svg

integration test:
  stage: test
  tags:
    - docker
  script:
    - pytest -x -s -v tests/integration

tox:
  image: robert96/tox:latest
  stage: test
  tags:
    - docker
  before_script:
    - tox --version
  script:
    - tox

docs:
  stage: docs
  artifacts:
    paths:
      - docs
  script:
  - cd docs
  - make html
  - cp -r _build/html ../docs

pages:
  stage: deploy
  dependencies:
    - unit tests
    - docs
  tags:
    - docker
  artifacts:
    paths:
    - public
  only:
    - master
  script:
    - cp -r docs/ public/
    - cp -r coverage/ public/coverage/