stages:
  - lint
  - test
  - functional
  - tox
  - docs
  - deploy

default:
  image: altwalker/graphwalker:4.3.1

  artifacts:
    paths:
      - "*.log"
    when: always

  before_script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements-dev.txt
    - python3 -m pip install -r requirements.txt --user

lint:
  stage: lint
  tags:
    - docker
  script:
    - flake8 altwalker tests

lint-docs:
  stage: lint
  tags:
    - docker
  script:
    - doc8 docs

unit-tests:
  stage: test
  tags:
    - docker
  artifacts:
    paths:
      - coverage/
      - "*.log"
    when: always
  script:
    - pytest tests/unit -s --cov=altwalker --cov-report term --cov-report html:coverage/ altwalker/
  after_script:
    - python3 -m pip install coverage-badge
    - coverage-badge -o coverage/coverage.svg

integration-test:
  stage: test
  tags:
    - docker
  script:
    - pytest -x -s -m "not dotnet" tests/integration

dotnet-integration-tests:
  stage: test
  image: altwalker/tests:dotnet-v2.1
  script:
    - pytest -x -s -m dotnet tests/integration

dotnet-functional-tests:
  stage: functional
  image: altwalker/tests:dotnet-v2.1
  before_script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt --user
    - python3 -m pip install --editable .
    - wget https://gitlab.com/altom/altwalker/dotnet-executor/-/jobs/artifacts/develop/download?job=dotnet%20pack -O artifacts.zip
    - unzip artifacts.zip
  script:
    - altwalker -v
    - altwalker init dotnet-example -l c# --no-git
    - dotnet restore dotnet-example/tests/tests.csproj -s AltwalkerExecutor/bin/Debug/ -s https://api.nuget.org/v3/index.json
    - cd dotnet-example
    - altwalker check -m models/default.json "random(vertex_coverage(100))"
    - altwalker verify tests/ -m models/default.json -x c# --executor-url http://localhost:4200/
    - altwalker online tests/ -m models/default.json "random(vertex_coverage(100))" -x c# --executor-url http://localhost:4200/
    - altwalker offline -m models/default.json "random(vertex_coverage(100))" --output-file steps.json
    - altwalker walk tests/ steps.json -x c# --executor-url http://localhost:4200/

python-functional-tests:
  stage: functional
  before_script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt --user
    - python3 -m pip install --editable .
  script:
    - altwalker --version
    - altwalker init python-example -l python --no-git
    - cd python-example
    - altwalker check -m models/default.json "random(vertex_coverage(100))"
    - altwalker verify tests -m models/default.json
    - altwalker online tests -m models/default.json "random(vertex_coverage(100))"
    - altwalker offline -m models/default.json "random(vertex_coverage(100))" --output-file steps.json
    - altwalker walk tests steps.json

http-functional-tests:
  stage: functional
  image: altwalker/tests:dotnet-v2.1
  before_script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt --user
    - python3 -m pip install --editable .
    - wget https://gitlab.com/altom/altwalker/dotnet-executor/-/jobs/artifacts/develop/download?job=dotnet%20pack -O artifacts.zip
    - unzip artifacts.zip
  script:
    - altwalker -v
    - altwalker init dotnet-example -l c# --no-git
    - dotnet restore dotnet-example/tests/tests.csproj -s AltwalkerExecutor/bin/Debug/ -s https://api.nuget.org/v3/index.json
    - cd dotnet-example
    - dotnet run --project tests/tests.csproj --server.urls=http://localhost:4200/ &
    - sleep 10
    - altwalker check -m models/default.json "random(vertex_coverage(100))"
    - altwalker verify tests/ -m models/default.json -x http --executor-url http://localhost:4200/
    - altwalker online tests/ -m models/default.json "random(vertex_coverage(100))" -x http --executor-url http://localhost:4200/
    - altwalker offline -m models/default.json "random(vertex_coverage(100))" --output-file steps.json
    - altwalker walk tests/ steps.json -x http --executor-url http://localhost:4200/

remote-graphwalker-functional-tests:
  stage: functional
  before_script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt --user
    - python3 -m pip install --editable .
  script:
    - gw --debug ALL online --service RESTFUL --port 8080 --verbose &
    - sleep 10
    - altwalker --version
    - altwalker init python-example -l python --no-git
    - cd python-example
    - altwalker check -m models/default.json "random(vertex_coverage(100))"
    - altwalker verify tests -m models/default.json
    - altwalker online tests -m models/default.json "random(vertex_coverage(100))" --gw-host localhost --gw-port 8080

tox:
  image: altwalker/tests:tox
  stage: tox
  only:
    - develop
  tags:
    - docker
  script:
    - tox

docs:
  stage: docs
  artifacts:
    paths:
      - documentation
  only:
    - master
  script:
    - python3 -m pip install --editable .
    - cd docs
    - make html
    - cp -r build/html ../documentation

pages:
  stage: deploy
  dependencies:
    - unit-tests
    - docs
  tags:
    - docker
  artifacts:
    paths:
      - public
  only:
    - master
  script:
    - cp -r documentation/ public/
    - cp -r coverage/ public/coverage/
