name: Docs

on:
  push:
    paths:
      - 'altwalker/**'
      - 'docs/**'
      - 'docs8.ini'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dev dependencies
      run: pip install -r requirements-dev.txt

    - name: Lint docs
      run: doc8 docs
