name: Unit Tests & Integration Tests

on:
  push:
    paths:
      - 'altwalker/**'
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 .

  unit:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/unit -x -s --cov=altwalker --cov-report term --cov-report html:coverage/ altwalker/

    - name: Upload log files
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: unit-logs
        path: '**/*.log'

  integration:
    runs-on: ubuntu-latest
    need: lint

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK 2.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '2.1'

    - uses: altwalker/setup-graphwalker@v1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install -r requirements.txt

    - name: Run integration tests
      run: |
        pytest tests/integration -x -s

    - name: Upload log files
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: integration-logs
        path: '**/*.log'
